// File dedicated for the Keeper mod, to make commenting it out easier. Somewhat. - [Ted]
class KeeperHandler : EventHandler
{
	override void PlayerDied(PlayerEvent e)
	{
		if(keeper_fixed_limit)
		{	
			// keeper code version that uses hard fixed limits
			let plr = HDPlayerPawn(players[e.PlayerNumber].mo);
			if (plr)
			{
				let restorer = StatRestorer(plr.GiveInventoryType('StatRestorer'));
				if (restorer)
				{	
					// old wounds
					if(plr.oldwoundcount > keeper_fixed_wounds)
					{
					restorer.Wounds = keeper_fixed_wounds;
					}
					else
					restorer.Wounds = plr.bloodloss;
					//biased balance change but i dislike blues vanishing on death
					restorer.Blues = int(plr.CountInv('HealingMagic'));
					//burns
					if(plr.burncount > keeper_fixed_burns)
					{
					restorer.Burns = keeper_fixed_burns;
					}
					else
					restorer.Burns = plr.burncount;
					
					// blood
					if(plr.bloodloss > keeper_fixed_blood)
					{
					restorer.Bloodloss = keeper_fixed_blood;
					}
					else
					restorer.Bloodloss = plr.bloodloss;
					
					// aggro
					if(plr.aggravateddamage > keeper_fixed_aggro)
					{
					restorer.Aggro = keeper_fixed_aggro;
					}
					else
					restorer.Aggro = plr.aggravateddamage;
					// i don't even know what diseases are from so they are cut for the moment.
				}
			}
		}
		else	//og keeper logic by ace below
		{
			let plr = HDPlayerPawn(players[e.PlayerNumber].mo);
			if (plr)
			{
				let restorer = StatRestorer(plr.GiveInventoryType('StatRestorer'));
				if (restorer)
				{
					restorer.Wounds = int(plr.oldwoundcount * clamp(keeper_percent_tissuedamage, 0, 1.0));
					restorer.Blues = int(plr.CountInv('HealingMagic') * clamp(keeper_percent_blues, 0, 1.0));
					restorer.Burns = int(plr.burncount * clamp(keeper_percent_burns, 0, 1.0));
					restorer.Aggro = int(plr.aggravateddamage * clamp(keeper_percent_aggro, 0, 1.0));
					restorer.Bloodloss = int(plr.bloodloss * clamp(keeper_percent_blood, 0, 1.0));

					Name diseaseClsName = 'DiseaseBase';
					if (keeper_percent_diseases > 0 && (class<Inventory>)(diseaseClsName))
					{
						for (Inventory next = plr.Inv; next != null; next = next.Inv)
						{
							if (next is diseaseClsName)
							{
								int amt = int(next.Amount * clamp(keeper_percent_diseases, 0, 1.0));
								if (amt > 0)
								{
									restorer.DiseaseClasses.Push(next.GetClass());
									restorer.DiseaseAmounts.Push(amt);
								}
							}
						}
					}
				}
			}
		}
	}
}

// [Ace] Defer restoring stats a few tics later otherwise the player's OnRespawn virtual will clear everything you do in PlayerRespawned.
class StatRestorer : Inventory
{
	override void DoEffect()
	{
		let plr = HDPlayerPawn(owner);
		if (plr && plr.Health > 0 && ++AliveTicker > 2)
		{
			plr.oldwoundcount = Wounds;
			plr.A_GiveInventory('HealingMagic', Blues);
			plr.aggravateddamage = Aggro;
			plr.burncount = Burns;
			if(keeper_fixed_limit)
			{
				plr.bloodloss = Bloodloss;
			}
			else
			{
				plr.bloodloss = min(HDCONST_MAXBLOODLOSS, plr.bloodloss + Bloodloss);
			}// [Ace] Add to PoF's bloodloss.

			for (int i = 0; i < DiseaseClasses.Size(); ++i)
			{
				plr.A_GiveInventory(DiseaseClasses[i], DiseaseAmounts[i]);
			}

			Destroy();
			return;
		}

		Super.DoEffect();
	}

	int AliveTicker;
	int Blues;
	int Wounds;
	int Aggro;
	int Burns;
	int Bloodloss;

	Array<class<Inventory> > DiseaseClasses;
	Array<int> DiseaseAmounts;

	Default
	{
		Inventory.MaxAmount 1;
	}
}

//	blues = 100%
//	
//	bloodloss
//	burns 
//	aggro
//	
//	
//
//
//